version: "3"
services:
  postgres_dev:
    image: postgres:13.1
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ghost_development
      POSTGRES_USER: ghost
      POSTGRES_PASSWORD: ghost

  postgres_test:
    image: postgres:13.1
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ghost_test
      POSTGRES_USER: ghost
      POSTGRES_PASSWORD: ghost

  adminer:
    image: adminer
    ports:
      - 8080:8080
